version:  '3.7'
services:
  mysql:
    image: mysql:5.7.23
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3310:3306'
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  adminer:
    image: adminer
    restart: on-failure
    links:
      - 'mysql:mysql'
    ports:
      - ${ADMINER_PORT}:8080
    depends_on:
      - mysql

  nginx:
    image: nginx:1.15.3-alpine
    restart: on-failure
    volumes:
      - ./public:/usr/src/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    env_file:
      - .env
    user: ${LOCAL_USER}
    volumes:
      - ./:/usr/src/app
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
